### ISSUE TITLE
Make super simple UI that coupon-holders can use to "approve" the CouponClipper contract

### ISSUE THREAD

**Issue by Austin-Williams** [Austin-Williams/coupon-clipper#2]
A simple, open source front-end that non-coders can use to "approve" and "unapprove" the CouponClipper contract.

**Comment by howardpen9** [comment]
Any framework you recommend? Maybe I can try to build it out.

**Comment by Austin-Williams** [comment]
Thanks to Lewi for making a UI: [https://esd.coupons/](https://esd.coupons/).
🙏🎉
