### ISSUE TITLE
Emit an event for setOffer

### ISSUE THREAD

**Issue by dmdque** [Austin-Williams/coupon-clipper#3]
For smart contract best practices (and so developers can more easily index the data), should emit an event for  `setOffer`.

Probably: `event OfferSet(address indexed account, uint256 offer)`

**Comment by Austin-Williams** [comment]
Good idea.
Let's add this to the next version.

**Comment by Austin-Williams** [comment]
Implemented in v2 [here](https://github.com/Austin-Williams/coupon-clipper/blob/main/contracts/CouponClipper.sol#L85).
